general.import = [ "tokyo-night.toml" ]

general.live_config_reload = true

[window]
opacity = 0.9
dynamic_padding = false

[window.padding]
x = 15
y = 10

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12.0
